export interface Stock { ticker: string; name: string; }

export const STOCKS: Stock[] = [
  { ticker: 'AAPL',  name: 'Apple Inc.' },
  { ticker: 'MSFT',  name: 'Microsoft Corporation' },
  { ticker: 'NVDA',  name: 'NVIDIA Corporation' },
  { ticker: 'GOOGL', name: 'Alphabet Inc. (Class A)' },
  { ticker: 'GOOG',  name: 'Alphabet Inc. (Class C)' },
  { ticker: 'AMZN',  name: 'Amazon.com Inc.' },
  { ticker: 'META',  name: 'Meta Platforms Inc.' },
  { ticker: 'TSLA',  name: 'Tesla Inc.' },
  { ticker: 'AVGO',  name: 'Broadcom Inc.' },
  { ticker: 'JPM',   name: 'JPMorgan Chase & Co.' },
  { ticker: 'LLY',   name: 'Eli Lilly and Company' },
  { ticker: 'V',     name: 'Visa Inc.' },
  { ticker: 'UNH',   name: 'UnitedHealth Group' },
  { ticker: 'XOM',   name: 'Exxon Mobil Corporation' },
  { ticker: 'MA',    name: 'Mastercard Incorporated' },
  { ticker: 'JNJ',   name: 'Johnson & Johnson' },
  { ticker: 'PG',    name: 'Procter & Gamble' },
  { ticker: 'WMT',   name: 'Walmart Inc.' },
  { ticker: 'HD',    name: 'Home Depot Inc.' },
  { ticker: 'MRK',   name: 'Merck & Co. Inc.' },
  { ticker: 'ABBV',  name: 'AbbVie Inc.' },
  { ticker: 'BAC',   name: 'Bank of America Corporation' },
  { ticker: 'CVX',   name: 'Chevron Corporation' },
  { ticker: 'KO',    name: 'Coca-Cola Company' },
  { ticker: 'COST',  name: 'Costco Wholesale Corporation' },
  { ticker: 'PEP',   name: 'PepsiCo Inc.' },
  { ticker: 'NFLX',  name: 'Netflix Inc.' },
  { ticker: 'TMO',   name: 'Thermo Fisher Scientific' },
  { ticker: 'CSCO',  name: 'Cisco Systems Inc.' },
  { ticker: 'ACN',   name: 'Accenture plc' },
  { ticker: 'MCD',   name: "McDonald's Corporation" },
  { ticker: 'ADBE',  name: 'Adobe Inc.' },
  { ticker: 'IBM',   name: 'International Business Machines' },
  { ticker: 'AMD',   name: 'Advanced Micro Devices' },
  { ticker: 'ORCL',  name: 'Oracle Corporation' },
  { ticker: 'INTC',  name: 'Intel Corporation' },
  { ticker: 'CRM',   name: 'Salesforce Inc.' },
  { ticker: 'ABT',   name: 'Abbott Laboratories' },
  { ticker: 'DIS',   name: 'Walt Disney Company' },
  { ticker: 'PFE',   name: 'Pfizer Inc.' },
  { ticker: 'NKE',   name: 'NIKE Inc.' },
  { ticker: 'PYPL',  name: 'PayPal Holdings Inc.' },
  { ticker: 'AMGN',  name: 'Amgen Inc.' },
  { ticker: 'MS',    name: 'Morgan Stanley' },
  { ticker: 'GS',    name: 'Goldman Sachs Group' },
  { ticker: 'T',     name: 'AT&T Inc.' },
  { ticker: 'VZ',    name: 'Verizon Communications' },
  { ticker: 'BRK.B', name: 'Berkshire Hathaway Inc.' },
  { ticker: 'SPGI',  name: 'S&P Global Inc.' },
  { ticker: 'AXP',   name: 'American Express Company' },
  { ticker: 'UBER',  name: 'Uber Technologies Inc.' },
  { ticker: 'BKNG',  name: 'Booking Holdings Inc.' },
  { ticker: 'ISRG',  name: 'Intuitive Surgical Inc.' },
  { ticker: 'LRCX',  name: 'Lam Research Corporation' },
  { ticker: 'KLAC',  name: 'KLA Corporation' },
  { ticker: 'AMAT',  name: 'Applied Materials Inc.' },
  { ticker: 'SNPS',  name: 'Synopsys Inc.' },
  { ticker: 'CDNS',  name: 'Cadence Design Systems' },
  { ticker: 'PANW',  name: 'Palo Alto Networks' },
  { ticker: 'CRWD',  name: 'CrowdStrike Holdings' },
  { ticker: 'DDOG',  name: 'Datadog Inc.' },
  { ticker: 'SNOW',  name: 'Snowflake Inc.' },
  { ticker: 'NET',   name: 'Cloudflare Inc.' },
  { ticker: 'ZS',    name: 'Zscaler Inc.' },
  { ticker: 'PLTR',  name: 'Palantir Technologies' },
  { ticker: 'SHOP',  name: 'Shopify Inc.' },
  { ticker: 'COIN',  name: 'Coinbase Global Inc.' },
  { ticker: 'SQ',    name: 'Block Inc.' },
  { ticker: 'ABNB',  name: 'Airbnb Inc.' },
  { ticker: 'DASH',  name: 'DoorDash Inc.' },
  { ticker: 'RIVN',  name: 'Rivian Automotive' },
  { ticker: 'TSM',   name: 'Taiwan Semiconductor Manufacturing' },
  { ticker: 'ASML',  name: 'ASML Holding N.V.' },
  { ticker: 'TXN',   name: 'Texas Instruments' },
  { ticker: 'QCOM',  name: 'Qualcomm Incorporated' },
  { ticker: 'MU',    name: 'Micron Technology' },
  { ticker: 'WFC',   name: 'Wells Fargo & Company' },
  { ticker: 'C',     name: 'Citigroup Inc.' },
  { ticker: 'SCHW',  name: 'Charles Schwab Corporation' },
  { ticker: 'BLK',   name: 'BlackRock Inc.' },
  { ticker: 'CAT',   name: 'Caterpillar Inc.' },
  { ticker: 'DE',    name: 'Deere & Company' },
  { ticker: 'BA',    name: 'Boeing Company' },
  { ticker: 'RTX',   name: 'RTX Corporation' },
  { ticker: 'LMT',   name: 'Lockheed Martin Corporation' },
  { ticker: 'GE',    name: 'GE Aerospace' },
  { ticker: 'HON',   name: 'Honeywell International' },
  { ticker: 'UPS',   name: 'United Parcel Service' },
  { ticker: 'FDX',   name: 'FedEx Corporation' },
  { ticker: 'F',     name: 'Ford Motor Company' },
  { ticker: 'GM',    name: 'General Motors Company' },
  { ticker: 'GILD',  name: 'Gilead Sciences Inc.' },
  { ticker: 'BIIB',  name: 'Biogen Inc.' },
  { ticker: 'REGN',  name: 'Regeneron Pharmaceuticals' },
  { ticker: 'VRTX',  name: 'Vertex Pharmaceuticals' },
  { ticker: 'BMY',   name: 'Bristol-Myers Squibb' },
  { ticker: 'MRNA',  name: 'Moderna Inc.' },
  { ticker: 'NVO',   name: 'Novo Nordisk A/S' },
  { ticker: 'AZN',   name: 'AstraZeneca PLC' },
  { ticker: 'NOW',   name: 'ServiceNow Inc.' },
  { ticker: 'INTU',  name: 'Intuit Inc.' },
  { ticker: 'WDAY',  name: 'Workday Inc.' },
  { ticker: 'TTD',   name: 'The Trade Desk Inc.' },
  { ticker: 'OKTA',  name: 'Okta Inc.' },
  { ticker: 'ZM',    name: 'Zoom Video Communications' },
  { ticker: 'TWLO',  name: 'Twilio Inc.' },
  { ticker: 'HUBS',  name: 'HubSpot Inc.' },
  { ticker: 'DOCU',  name: 'DocuSign Inc.' },
  { ticker: 'NIO',   name: 'NIO Inc.' },
  { ticker: 'BIDU',  name: 'Baidu Inc.' },
  { ticker: 'BABA',  name: 'Alibaba Group Holding' },
  { ticker: 'JD',    name: 'JD.com Inc.' },
  { ticker: 'PDD',   name: 'PDD Holdings Inc.' },
  { ticker: 'SAP',   name: 'SAP SE' },
  { ticker: 'WBA',   name: 'Walgreens Boots Alliance' },
  { ticker: 'CVS',   name: 'CVS Health Corporation' },
  { ticker: 'UNP',   name: 'Union Pacific Corporation' },
  { ticker: 'CSX',   name: 'CSX Corporation' },
  { ticker: 'NEE',   name: 'NextEra Energy Inc.' },
  { ticker: 'SO',    name: 'Southern Company' },
  { ticker: 'D',     name: 'Dominion Energy Inc.' },
  { ticker: 'DUK',   name: 'Duke Energy Corporation' },
  { ticker: 'AMT',   name: 'American Tower Corporation' },
  { ticker: 'PLD',   name: 'Prologis Inc.' },
  { ticker: 'O',     name: 'Realty Income Corporation' },
  { ticker: 'SPG',   name: 'Simon Property Group' },
  { ticker: 'EQIX',  name: 'Equinix Inc.' },
  { ticker: 'DLR',   name: 'Digital Realty Trust' },
  { ticker: 'GOOG',  name: 'Alphabet Class C' },
  { ticker: 'MMM',   name: '3M Company' },
  { ticker: 'PM',    name: 'Philip Morris International' },
  { ticker: 'MO',    name: 'Altria Group Inc.' },
];

export function searchStocks(query: string): Stock[] {
  if (!query.trim()) return [];
  const q = query.toUpperCase();
  const ql = query.toLowerCase();
  const exact: Stock[] = [];
  const startsWith: Stock[] = [];
  const contains: Stock[] = [];
  for (const s of STOCKS) {
    if (s.ticker === q) { exact.push(s); continue; }
    if (s.ticker.startsWith(q)) { startsWith.push(s); continue; }
    if (s.name.toLowerCase().includes(ql)) { contains.push(s); continue; }
  }
  return [...exact, ...startsWith, ...contains].slice(0, 8);
}
