name = "primitive-ontology"
main = "server.ts"
compatibility_date = "2026-05-12"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = false

[env.production]
route = "ontology.primitive-os.cc/*"

[assets]
directory = "./dist"
binding = "ASSETS"
